project:
  type: website

website:
  back-to-top-navigation: true
  title: "Data Science and Analytics"

  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - href: http://shriya-chinthak.georgetown.domains
        text: About Me

  sidebar:
    style: "docked"
    search: false
    contents:
    - href: https://github.com/anly501/dsan-5000-project-schinthak
      text: Code
    - href: https://github.com/anly501/dsan-5000-project-schinthak/tree/main/data
      text: Data
    - href: introduction.qmd
      text: Introduction
    - href: data-gathering.qmd
      text: Data Gathering
    - href: data-cleaning.qmd
      text: Data Cleaning
    - href: data-exploration.qmd
      text: Data Exploration
    - href: naive-bayes.qmd
      text: Naive Bayes
    - href: dr.qmd
      text: Dimensionality Reduction
    - href: clustering.qmd
      text: Clustering
    - section: Decision Trees
      contents:
        - href: classification.qmd
          text: Classification
    - href: arm.qmd
      text: ARM
    - href: conclusions.qmd
      text: Conclusions

format:
  html:
    theme: minty
    css: styles.css
    toc: true
