project:
  type: website

website:
  title: ""
  search: false
  page-navigation: false
  sidebar: false
  navbar: false
  

format:
  html:
    theme: simplex
    page-layout: full
    toc: false




